services:
  - type: web
    name: discord-music-bot
    env: docker
    region: singapore
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: DISCORD_TOKEN
        sync: false
      - key: PORT
        value: 3000
      - key: LOG_LEVEL
        value: info
      - key: DB_PATH
        value: /data/ragabot.db
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: discord-bot-data
      mountPath: /data
      sizeGB: 1
