services:
  - type: web
    name: discord-music-bot
    runtime: node
    region: singapore
    plan: free
    buildCommand: npm ci --only=production
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DISCORD_TOKEN
        sync: false
      - key: PORT
        value: 3000
      - key: LOG_LEVEL
        value: info
    healthCheckPath: /health
    autoDeploy: true
