services:
  - type: web
    name: discord-music-bot
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DISCORD_TOKEN
        sync: false
      - key: PORT
        value: 3000
    healthCheckPath: /health
